# Generated by Django 4.2 on 2023-06-23 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birthday', models.DateField(verbose_name='data de nascimento')),
                ('gender', models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino')], max_length=1, verbose_name='sexo')),
                ('phone', models.IntegerField(verbose_name='telefone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'db_table': 'profile',
            },
        ),
    ]
