# Generated by Django 4.2 on 2023-07-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-available", "-price", "name"],
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, max_length=256, null=True, verbose_name="descrição"
            ),
        ),
    ]
