# Generated by Django 4.2 on 2023-07-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="size",
            field=models.CharField(
                choices=[
                    ("p", "P"),
                    ("m", "M"),
                    ("g", "G"),
                    ("gg", "GG"),
                    ("xg", "XG"),
                ],
                max_length=6,
                verbose_name="tamanho",
            ),
        ),
    ]
